/*
 * File: app/view/CarListings.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HWTsaProject.view.CarListings', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.carlistings',

    requires: [
        'HWTsaProject.view.CarListingsViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.XTemplate',
        'Ext.form.field.ComboBox'
    ],

    viewModel: {
        type: 'carlistings'
    },
    frame: true,
    height: 705,
    width: 654,
    title: 'Car Listing',
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'combobox',
            flex: 1,
            fieldLabel: 'Label',
            store:'MyArrayStore',
            displayField: 'language',
            renderTo: Ext.getBody(),
            queryMode: 'local'
        },
        {
            xtype: 'gridpanel',
            flex: 1,
            autoLoad: true,
            store: 'CarDataStore',
            viewConfig: {
                height: 344,
                width: 541
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'manufacturer',
                    text: 'Manufacturer'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'model',
                    text: 'Model'
                },
                {
                    xtype: 'gridcolumn',
                    sortable: true,
                    dataIndex: 'price',
                    text: 'Price'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'wiki',
                    text: 'Wiki'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'img',
                    text: 'Img'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'quality',
                    text: 'Quality'
                }
            ],
            listeners: {
                select: 'onGridpanelSelect'
            }
        },
        {
            xtype: 'panel',
            flex: 1,
            itemId: 'detailPanel',
            tpl: [
                '<img src="data/{img}" style="float: right" />',
                '',
                'Manufacturer: {manufacturer} ',
                'Model: <a href="{wiki}" target="_blank">{model}</a><br>',
                'Price: {price:usMoney}'
            ],
            title: 'My Panel'
        }
    ],

    onGridpanelSelect: function(rowmodel, record, index, eOpts) {
        console.log(record);
        // grab a reference to the detailPanel via itemId
        // the # in front of the id indicates that we would like to grab a reference by
        var detailPanel = this.child('#detailPanel');
        // update the detailPanel with data
        // this will trigger the tpl to become updates
        detailPanel.update(record.data);
    }

});